stages:
  - build
  - test
  - publish

build-mongo:
  stage: build
  image: microsoft/dotnet:sdk
  tags:
    - docker
  script:
    - dotnet publish src/i18u.Repositories.Mongo -c Release -o out --no-restore
    - cp src/i18u.Repositories.Mongo/out ./out/i18u.Repositories.Mongo
  artifacts:
    paths:
      - out

test-mongo:
  stage: test
  image: microsoft/dotnet:sdk
  dependencies: []
  tags:
    - docker
  script:
    - dotnet test src/i18u.Repositories.Mongo /p:CollectCoverage=true 
  coverage: '/i18u\.Repositories\.Mongo \| ([\d\.]+)%/'

.publish-mongo:
  stage: publish
  dependencies:
    - build-mongo
  only:
    - tags
  tags:
    - docker
  script:
    - dotnet test src /p:CollectCoverage=true 
  coverage: '/i18u\.Repositories\.Mongo \| ([\d\.]+)%/'